apiVersion: v1
kind: Service
metadata:
  name: company-site
  labels:
    name: company-site
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32767
  type: "NodePort"
  selector:
    name: company-site
