apiVersion: v1
kind: Service
metadata:
  name: company-boss
  labels:
    name: company-boss
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32766
  type: "NodePort"
  selector:
    name: company-boss
